### ISSUE TITLE
make errror on mac 10.10

### ISSUE THREAD

**Issue by jiayouxjh** [yangyangwithgnu/autoshadower#3]
Linking CXX executable autoshadower
Undefined symbols for architecture x86_64:
  "_iconv", referenced from:
      Webpage::convertCharset(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in Webpage.o
  "_iconv_close", referenced from:
      Webpage::convertCharset(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in Webpage.o
  "_iconv_open", referenced from:
      Webpage::convertCharset(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in Webpage.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [autoshadower] Error 1
make[1]: *** [CMakeFiles/autoshadower.dir/all] Error 2
make: *** [all] Error 2

**Comment by yangyangwithgnu** [comment]
兄弟麻烦邮件联系我下 yangyangwithgnu[AT]yeah.net

**Comment by yangyangwithgnu** [comment]
先将 build/CMakeLists.txt 中的  
```
TARGET_LINK_LIBRARIES(hardseed curl pthread)
```
替换成
```
TARGET_LINK_LIBRARIES(hardseed curl pthread iconv)
```
其他同 linux 构建方法。
